export const registeredPages = {
    HOMEPAGE: 'homepage',
    ABOUT: 'aboutUs',
    BLOG: 'blog',
    AUTHOR: 'user',
    CATEGORY: 'category',
    SINGLE_BLOG: 'post',
    CASE_STUDY: 'caseStudy',
    TESTIMONIALS: 'testimonials',
    PORTFOLIO: 'portfolio',
    WORK_WITH_ME: 'workWithMe',
    SERVICES: 'services',
    SINGLE_SERVICES: 'service',
    SEO_APPROACH: 'seoApproach',
    CONTACT: 'contact',
    DETAILED_CASE_STUDY: 'detailedCaseStudy',
    DETAILED_SERVICES: 'seoServices',
    CONSULTING: 'consulting',
    CONSULTING_SERVICES: 'consultingService',
    DETAILED_CONSULTING_SERVICES: 'consultingServices',
    SINGLE_INDUSTRY:'industry',
    INDUSTRIES:'industries',
    DETAILED_INDUSTRY_SERVICES: 'industryServices',
    PRIVACY_POLICY: 'privacyPolicy',
    TERMS_OF_SERVICE: 'termsOfService',
    NOT_FOUND_PAGE: 'notFound',
    THANK_YOU: 'thankYou',

}
