export const registeredPages = {
    HOMEPAGE: 'homepage',
    ABOUT: 'aboutUs',
    BLOG: 'blog',
    AUTHOR: 'user',
    CATEGORY: 'category',
    SINGLE_BLOG: 'post',
    CASE_STUDY: 'caseStudy',
    TESTIMONIALS: 'testimonials',
    PORTFOLIO: 'portfolio',
    WORK_WITH_ME: 'workWithMe',
    SERVICES: 'services',
    SEO_APPROACH: 'seoApproach',
    CONTACT: 'contact',
}
