export const registeredPages = {
    HOMEPAGE: 'homepage',
    ABOUT: 'aboutUs',
    BLOG: 'blog',
    AUTHOR: 'user',
    CATEGORY: 'category',
    SINGLE_BLOG: 'post',
    CASE_STUDY: 'caseStudy',
    TESTIMONIALS: 'testimonials',
    PORTFOLIO: 'portfolio',
    WORK_WITH_ME: 'workWithMe',
    SERVICES: 'services',
    SINGLE_SERVICES: 'service',
    SEO_APPROACH: 'seoApproach',
    CONTACT: 'contact',
    DETAILED_CASE_STUDY: 'detailedCaseStudy',
    DETAILED_SERVICES: 'seoServices',
    CONSULTING_SERVICES: 'consultingService',
    DETAILED_CONSULTING_SERVICES: 'consultingServices',
    SINGLE_INDUSTRY:'industry',
    DETAILED_INDUSTRY_SERVICES: 'industryServices',

}
